import { test, expect, type Page } from '@playwright/test'
import { randomUUID } from 'node:crypto'
test.skip(process.env.E2E_MODE === 'mock', 'REST test requires REST mode')
const today = () => new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai' }).format(new Date())
const photo = 'src/assets/lake-editorial.jpg'
async function register(page: Page, username: string, password: string, nickname: string) {
  await page.goto('/')
  await page.getByRole('button', { name: '没有账号，去注册' }).click()
  await page.getByLabel('用户名', { exact: true }).fill(username)
  await page.getByLabel('密码', { exact: true }).fill(password)
  await page.getByLabel('昵称', { exact: true }).fill(nickname)
  await page.getByRole('button', { name: '注册并登录', exact: true }).click()
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible()
}
test('mobile REST flow persists across refresh and enforces real checkin', async ({ page, browser }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  const suffix = randomUUID().replaceAll('-', '').slice(0, 10)
  const password = randomUUID()
  const title = '浏览器联调模拟-' + suffix
  const poiName = '浏览器模拟地点-' + suffix
  await register(page, 'ui_a_' + suffix, password, '浏览器模拟提问者')
  await page.goto('/questions/new')
  await page.getByLabel('问题标题').fill(title)
  await page.getByLabel('详细问题').fill('这条内容用于前后端联调，地点后来怎么样了？')
  await page.locator('input[type=file]').setInputFiles(photo)
  await expect(page.getByAltText('参照照片预览')).toBeVisible()
  await page.getByLabel('城市', { exact: true }).fill('联调模拟城市')
  await page.getByLabel('具体地点', { exact: true }).fill(poiName)
  await page.getByLabel('经度', { exact: true }).fill('100.1789')
  await page.getByLabel('纬度', { exact: true }).fill('27.1156')
  await page.getByLabel('回答开始日期').fill(today())
  await page.getByLabel('回答结束日期').fill(today())
  await page.getByLabel('拍摄建议').fill('从南侧拍摄')
  await page.getByRole('button', { name: '查看发布预览' }).click()
  await page.getByRole('button', { name: '确认发布' }).click()
  await expect(page.getByRole('heading', { name: '问题已发布' })).toBeVisible()
  const id = (await page.locator('.published-id').innerText()).replace('问题编号：', '').trim()
  await page.goto('/questions/' + id)
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  await expect(page.getByAltText('问题参照照片')).toBeVisible()
  await expect(page.getByText('这是你自己发布的问题，不能领取。')).toBeVisible()

  const context = await browser.newContext({ baseURL: process.env.E2E_BASE_URL || 'http://127.0.0.1:5173', viewport: { width: 390, height: 844 } })
  const traveler = await context.newPage()
  traveler.on('pageerror', e => errors.push(e.message))
  await register(traveler, 'ui_b_' + suffix, password, '浏览器模拟旅行者')
  await traveler.goto('/trips/new')
  await traveler.locator('.rest-location select').selectOption({ label: '联调模拟城市 · ' + poiName + '（100.1789, 27.1156）' })
  await traveler.getByLabel('到达日期').fill(today())
  await traveler.getByLabel('离开日期').fill(today())
  await traveler.getByRole('button', { name: '保存行程', exact: true }).click()
  await expect(traveler).toHaveURL(/\/trips$/)

  const secondDevice = await browser.newContext({ baseURL: process.env.E2E_BASE_URL || 'http://127.0.0.1:5173' })
  const remote = await secondDevice.newPage()
  await remote.goto('/trips')
  await remote.getByLabel('用户名', { exact: true }).fill('ui_b_' + suffix)
  await remote.getByLabel('密码', { exact: true }).fill(password)
  await remote.getByRole('button', { name: '登录', exact: true }).click()
  await expect(remote.locator('.trip-list')).toContainText(poiName)
  await expect(remote.locator('.trip-list')).toContainText('当前行程')
  await secondDevice.close()

  await traveler.goto('/discover')
  await traveler.getByRole('tab', { name: '匹配我的行程' }).click()
  await expect(traveler.getByRole('heading', { name: title })).toBeVisible()
  await traveler.goto('/questions/' + id)
  await traveler.getByRole('button', { name: /我去看看/ }).click()
  await expect(traveler.getByRole('button', { name: /继续写回信/ })).toBeVisible()
  await expect(traveler.getByRole('button', { name: '取消领取', exact: true })).toHaveCount(0)
  await traveler.getByRole('button', { name: /继续写回信/ }).click()
  await traveler.getByLabel('当前位置经度').fill('0')
  await traveler.getByLabel('当前位置纬度').fill('0')
  await traveler.getByRole('button', { name: '确认签到', exact: true }).click()
  await expect(traveler.getByRole('alert')).toContainText('超出 300 米')
  await traveler.getByLabel('当前位置经度').fill('100.1789')
  await traveler.getByLabel('当前位置纬度').fill('27.1156')
  await traveler.getByRole('button', { name: '确认签到', exact: true }).click()
  await expect(traveler.getByText(/签到成功，请在/)).toBeVisible()
  const fileChooser = traveler.waitForEvent('filechooser')
  await traveler.getByRole('button', { name: /点击上传现场照片/ }).click()
  await (await fileChooser).setFiles(photo)
  await expect(traveler.getByAltText('现场照片', { exact: true })).toBeVisible()
  await traveler.locator('textarea').fill('浏览器联调模拟回信：这里还在。')
  await traveler.getByRole('checkbox').check()
  await traveler.getByRole('button', { name: /寄出这封回信/ }).click()
  await expect(traveler).toHaveURL(new RegExp('/questions/' + id + '$'))
  await expect(traveler.getByText('浏览器联调模拟回信：这里还在。', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('浏览器联调模拟回信：这里还在。', { exact: true })).toBeVisible()
  await expect(page.getByAltText('浏览器模拟旅行者的现场照片')).toBeVisible()
  await page.getByRole('button', { name: '退出登录' }).click()
  await expect(page.getByRole('button', { name: '登录', exact: true })).toBeVisible()
  await context.close()
  expect(errors).toEqual([])
})
