import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'
test('publish navigation and missing location feedback remain visible', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '没有账号，去注册' }).click()
  await page.getByLabel('用户名', { exact: true }).fill('pub_' + randomUUID().replaceAll('-', '').slice(0, 12))
  await page.getByLabel('昵称', { exact: true }).fill('发布反馈回归用户')
  await page.getByLabel('密码', { exact: true }).fill(randomUUID())
  await page.getByRole('button', { name: '注册并登录', exact: true }).click()
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible()
  await page.getByRole('tab', { name: /发布/ }).click()
  await expect(page.getByRole('heading', { name: '发布问题', exact: true })).toBeVisible()
  await page.getByLabel('问题标题').fill('发布校验回归')
  await page.getByLabel('详细问题').fill('请检查缺少地点时是否有明确提示')
  await page.locator('input[type=file]').setInputFiles('src/assets/lake-editorial.jpg')
  await expect(page.getByAltText('参照照片预览')).toBeVisible()
  const today = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai' }).format(new Date())
  await page.getByLabel('回答开始日期').fill(today)
  await page.getByLabel('回答结束日期').fill(today)
  let publishes = 0
  page.on('request', r => { if (r.method() === 'POST' && new URL(r.url()).pathname === '/v1/capsules') publishes++ })
  await page.getByRole('button', { name: '查看发布预览' }).click()
  await expect(page.getByRole('alert').filter({ hasText: '请填写城市' }).first()).toBeVisible()
  await expect(page.getByRole('alert').filter({ hasText: '请填写具体地点' }).first()).toBeVisible()
  await page.getByLabel('城市', { exact: true }).fill('测试城市')
  await page.getByLabel('具体地点', { exact: true }).fill('测试地点')
  await page.getByRole('button', { name: '查看发布预览' }).click()
  await expect(page).toHaveURL(/\/questions\/new$/)
  await expect(page.getByRole('alert').filter({ hasText: '经纬度' }).first()).toBeVisible()
  await page.getByLabel('经度', { exact: true }).fill('181')
  await page.getByLabel('纬度', { exact: true }).fill('0')
  await page.getByRole('button', { name: '查看发布预览' }).click()
  await expect(page).toHaveURL(/\/questions\/new$/)
  await expect(page.getByRole('alert').filter({ hasText: '经纬度' }).first()).toBeVisible()
  await page.getByLabel('经度', { exact: true }).fill('0')
  await page.getByRole('button', { name: '查看发布预览' }).click()
  await expect(page.getByRole('heading', { name: '发布预览', exact: true })).toBeVisible()
  expect(publishes).toBe(0)
})
